---
resources:
- name: pipeline
  type: git
  source:
    uri: https://github.com/gibbster/concourse-go-pipeline.git
- name: application
  type: git
  source:
    uri: https://github.com/gibbster/simple-go-web-app.git
- name: slack
  type: slack-notification
  source:
    url: {{slack-webhook-url}}
- name: version
  type: semver
  source:
    bucket: concourse-go-pipeline
    key: current-version
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}
    region_name: us-west-2
    initial_version: 1.0.0
- name: s3-product-rc
  type: s3
  source:
    bucket: concourse-go-pipeline
    regexp: simple-go-web-app-(.*)
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}
    region_name: us-west-2
- name: docker-product-rc
  type: docker-image
  source:
    repository: 287222052256.dkr.ecr.us-west-2.amazonaws.com/davidpipeline
    aws_access_key_id: {{ecr-access-key-id}}
    aws_secret_access_key: {{ecr-secret-access-key}}


jobs:
- name: test-app
  public: true
  plan:
  - get: pipeline
  - get: application
    trigger: true
  - task: web-app-tests
    file: pipeline/ci/task_run_tests.yml
    on_success:
      put: slack
      params:
        text: |
          :white_check_mark: Tests ran successfully
          http://192.168.100.4:8080/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME

- name: build-rc
  public: true
  serial_groups: [version]
  plan:
  - get: pipeline
  - get: application
    passed: [test-app]
    trigger: true
  - get: version
    params: {pre: rc}
  - task: build-rc
    file: pipeline/ci/task_build_rc.yml
  - put: version
    params: {file: version/number}
  - put: s3-product-rc
    params: {file: build-artifacts/simple-go-web-app-*}
  - put: docker-product-rc
    params: 
      build: pipeline/ci
      tag: version/number
      tag_prefix: v
    build-args:
      version: build-artifacts/simple-go-web-app
    on_success:
      put: slack
      params:
        text: |
          :white_check_mark: Release candidate built successfully
          http://192.168.100.4:8080/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME

resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
